# 2.2 数据操作

In [6]:
import torch

torch.manual_seed(0)
torch.cuda.manual_seed(0)
print(torch.__version__)

1.3.1


## 2.2.1 创建`Tensor`

创建一个5x3的未初始化的`Tensor`：

In [7]:
x = torch.empty(5, 3)
print(x)

tensor([[-2.7857e+10,  4.5580e-41, -2.7857e+10],
        [ 4.5580e-41,  4.4842e-44,  0.0000e+00],
        [ 1.5695e-43,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  8.9683e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


创建一个5x3的随机初始化的`Tensor`:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])


创建一个5x3的long型全0的`Tensor`:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接根据数据创建:

In [13]:
x = torch.tensor([5.5, 3])
print(x)
print(x.dtype)

tensor([5.5000, 3.0000])
torch.float32


还可以通过现有的`Tensor`来创建，此方法会默认重用输入`Tensor`的一些属性，例如数据类型，除非自定义数据类型。

In [18]:
x = x.new_ones(5, 3, dtype=torch.float64)      # 返回的tensor默認具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 指定新的數據類型
print(x)                                    

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1227, -1.1088,  1.6254],
        [ 1.2333, -0.1832, -1.3140],
        [-1.6894,  1.2525, -0.5545],
        [ 0.3019,  1.1295,  1.7179],
        [-0.8507, -0.8486, -0.1848]])


我們可以通過`shape`或者`size()`來獲取`Tensor`的形狀:

In [15]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


> 注意：返回的torch.Size其實就是一個tuple, 支持所有tuple的操作。

## 2.2.2 操作
### 算術操作
* **加法形式一**

In [20]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.0639, -0.5093,  1.6906],
        [ 1.7793,  0.0040, -1.2800],
        [-0.7452,  2.1327, -0.5533],
        [ 0.8955,  1.5453,  2.1356],
        [-0.5796, -0.1564,  0.0191]])


* **加法形式二**

In [22]:
print(torch.add(x, y))

tensor([[ 1.0639, -0.5093,  1.6906],
        [ 1.7793,  0.0040, -1.2800],
        [-0.7452,  2.1327, -0.5533],
        [ 0.8955,  1.5453,  2.1356],
        [-0.5796, -0.1564,  0.0191]])


In [23]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.0639, -0.5093,  1.6906],
        [ 1.7793,  0.0040, -1.2800],
        [-0.7452,  2.1327, -0.5533],
        [ 0.8955,  1.5453,  2.1356],
        [-0.5796, -0.1564,  0.0191]])


* **加法形式三、inplace**

In [24]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.0639, -0.5093,  1.6906],
        [ 1.7793,  0.0040, -1.2800],
        [-0.7452,  2.1327, -0.5533],
        [ 0.8955,  1.5453,  2.1356],
        [-0.5796, -0.1564,  0.0191]])


> **注：PyTorch操作inplace版本都有后缀"_", 例如`x.copy_(y), x.t_()`**

### 索引
我们还可以使用类似NumPy的索引操作来访问`Tensor`的一部分，需要注意的是：**索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。** 

In [26]:
print(x)
y = x[0, :]
print(x[0, :])
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了

tensor([[ 1.1227, -0.1088,  2.6254],
        [ 1.2333, -0.1832, -1.3140],
        [-1.6894,  1.2525, -0.5545],
        [ 0.3019,  1.1295,  1.7179],
        [-0.8507, -0.8486, -0.1848]])
tensor([ 1.1227, -0.1088,  2.6254])
tensor([2.1227, 0.8912, 3.6254])
tensor([2.1227, 0.8912, 3.6254])


### 改变形状
用`view()`来改变`Tensor`的形状：

In [29]:
y = x.view(15)
z = x.view(-1, 5)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


**注意`view()`返回的新tensor与源tensor共享内存，也即更改其中的一个，另外一个也会跟着改变。**

In [28]:
x += 1
print(x)
print(y) # 也加了1

tensor([[ 3.1227,  1.8912,  4.6254],
        [ 2.2333,  0.8168, -0.3140],
        [-0.6894,  2.2525,  0.4455],
        [ 1.3019,  2.1295,  2.7179],
        [ 0.1493,  0.1514,  0.8152]])
tensor([ 3.1227,  1.8912,  4.6254,  2.2333,  0.8168, -0.3140, -0.6894,  2.2525,
         0.4455,  1.3019,  2.1295,  2.7179,  0.1493,  0.1514,  0.8152])


如果不想共享内存，推荐先用`clone`创造一个副本然后再使用`view`。

In [30]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 2.1227,  0.8912,  3.6254],
        [ 1.2333, -0.1832, -1.3140],
        [-1.6894,  1.2525, -0.5545],
        [ 0.3019,  1.1295,  1.7179],
        [-0.8507, -0.8486, -0.1848]])
tensor([ 3.1227,  1.8912,  4.6254,  2.2333,  0.8168, -0.3140, -0.6894,  2.2525,
         0.4455,  1.3019,  2.1295,  2.7179,  0.1493,  0.1514,  0.8152])


另外一个常用的函数就是`item()`, 它可以将一个标量`Tensor`转换成一个Python number：

In [31]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.9513])
-1.9512622356414795


## 2.2.3 广播机制

In [32]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


## 2.2.4 運算的內存開銷

In [39]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)
print(id_before)
print(id(y))

False
139703919108168
139703919051112


In [36]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [37]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before)

True


## 2.2.5 `Tensor`和NumPy相互轉換
**`numpy()`和`from_numpy()`這兩個函數產生的`Tensor`和NumPy array實際是使用的相同的內存，改變其中一個時另一個也會改變！！！**
### `Tensor`轉NumPy

In [40]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


### NumPy數組轉`Tensor`

In [41]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


直接用`torch.tensor()`將NumPy數組轉換成`Tensor`，該方法總是會進行數據拷貝，返回的`Tensor`和原來的數據不再共享內存。

In [42]:
# 用torch.tensor()轉換時不會共享內存
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


## 2.2.6 `Tensor` on GPU

In [44]:
# 以下代碼只有在PyTorch GPU版本上才會執行
if torch.cuda.is_available():
    device = torch.device("cuda")          # GPU
    y = torch.ones_like(x, device=device)  # 直接創建一個在GPU上的Tensor
    x = x.to(device)                       # 等價於 .to("cuda")
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # to()還可以同時更改數據類型